version: '3.5'
services:
    nginx:
        build: ./docker/images/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./application:/var/www/html
            - ./logs:/var/log/nginx
            - ./docker/images/certbot/conf:/etc/letsencrypt
            - ./docker/images/certbot/www:/var/www/certbot
        restart: unless-stopped
        networks:
            - host
        links:
            - app
    app:
        build: ./docker/images/php
        working_dir: /var/www/html
        links:
            - postgresql
        networks:
            - host
        volumes:
            - ./application:/var/www/html
        restart: unless-stopped
    postgresql:
        image: postgres:15.1
        ports:
            - "5432:5432"
        networks:
            - host
        volumes:
            - ./postgresqldb:/var/lib/postgresql/data
            - ./dumps:/dumps
        restart: unless-stopped
        environment:
            POSTGRES_USER: evalite_user
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: evalite_db
    supervisor:
        build: ./docker/images/supervisor
        working_dir: /var/www/html
        depends_on:
            - postgresql
        links:
            - postgresql
        networks:
            - host
        volumes:
            - ./application:/var/www/html
            # - ./docker/images/supervisor/files:/etc/supervisor/conf.d/
        restart: unless-stopped
    certbot:
        image: certbot/certbot
        volumes:
            - ./docker/images/certbot/conf:/etc/letsencrypt
            - ./docker/images/certbot/www:/var/www/certbot
networks:
    host:
        driver: bridge
