version: '3.5'
services:
    nginx:
        build: ./docker/images/nginx
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - ./docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./application:/var/www/html
            - ./logs:/var/log/nginx
        networks:
            - host
        links:
            - app
    app:
        build: ./docker/images/php
        working_dir: /var/www/html
        links:
            - postgresql
        networks:
            - host
        volumes:
            - ./application:/var/www/html
    postgresql:
        image: postgres:15.1
        ports:
            - "5432:5432"
        networks:
            - host
        volumes:
            - ./postgresqldb:/var/lib/postgresql/data
            - ./dumps:/dumps
        environment:
            POSTGRES_USER: evalite_user
            POSTGRES_PASSWORD: pQLkm8NOkS0gOBox
            POSTGRES_DB: evalite_db
networks:
    host:
        driver: bridge
